CREATE TABLE IF NOT EXISTS "AUTHENTICATION_LOG" 
   ("ID" VARCHAR2(200) NOT NULL, 
	"VERSION" NUMBER(15) NOT NULL, 
	"REALM" VARCHAR2(100) NOT NULL, 
	"CREATOR" VARCHAR2(100) NOT NULL, 
	"CREATION_INSTANT" NUMBER(19) NOT NULL, 
	"CREATOR_APPLICATION_ID" VARCHAR2(64) NOT NULL, 
	"CUID" VARCHAR2(64) NOT NULL,
	"AUTHENTICATED_TIME" NUMBER(19) NOT NULL
   )
 as select * from csvread('classpath:data/authentication_log.csv');